#!/usr/bin/env bash
# OneShelf: install and start.
#
#   ./install.sh
#
# Safe to run again at any time: it never overwrites your .env, never deletes a volume, and never
# touches anything on this machine that does not belong to OneShelf.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=deploy/lib.sh
. "$ROOT/deploy/lib.sh"
require_repo_root "$ROOT"

say "OneShelf — a personal reading library that lives on your own machine."
say ""

step "Looking for a container runtime"
RUNTIME="$(detect_runtime)"
ok "using $RUNTIME ($("$RUNTIME" --version 2>/dev/null | head -1))"

step "Looking for Compose"
COMPOSE="$(detect_compose "$RUNTIME")"
ok "using $COMPOSE"

step "Configuration"
ensure_env "$ROOT"
say "    edit .env to change where OneShelf listens or where your library is kept"

step "Preparing OneShelf's own directories"
mapfile -t DIRS < <(prepare_directories "$ROOT")
for d in "${DIRS[@]}"; do say "    $d"; done
# The key for saved source logins is generated by OneShelf itself, on first start, on its own volume —
# there is no secret to put in .env, so none is printed here or anywhere else.

step "Building the image (the first time takes a few minutes)"
compose_cmd build

step "Starting OneShelf"
compose_cmd up -d

IMAGE="$(env_value "$ROOT" ONESHELF_IMAGE "oneshelf:local")"
fix_ownership_if_needed "$IMAGE" "${DIRS[@]}" || true

URL="$(oneshelf_url "$ROOT")"
step "Waiting for OneShelf to be ready"
READY=""; READY_STATUS=0
READY="$(wait_for_ready "$URL")" || READY_STATUS=$?
if [ "$READY_STATUS" -eq 0 ]; then
  ok "ready"
elif [ "$READY_STATUS" -eq 3 ]; then
  warn "skipping the readiness check; open $URL yourself to confirm"
  READY=""
else
  diagnose "$URL"
  exit 1
fi

if [ -n "$READY" ]; then
  if probe "$URL/api/health" >/dev/null; then ok "health check passed"; else
    diagnose "$URL"; exit 1
  fi
fi

say ""
say "${_b}OneShelf is running at ${URL}${_r}"
say ""
say "  Your library is kept in the directories listed above and survives restarts and updates."
say "  Update:     ./update.sh"
say "  Stop:       ./uninstall.sh          (keeps all your data)"
say "  Logs:       $COMPOSE -f $COMPOSE_FILE_REL logs -f"
say ""
say "  By default OneShelf listens on this machine only. To reach it from other devices on your"
say "  own network, set ONESHELF_BIND and ONESHELF_TRUSTED_NETWORKS in .env, then ./install.sh again."
